#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
